spring.application.name=buildmart
spring.datasource.url=jdbc:mysql://localhost:3306/buildmart
spring.datasource.username=root
spring.datasource.password=Deep@1972

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true